# Generated by Django 5.1.5 on 2025-01-31 16:07

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('question_es', models.CharField(max_length=255, null=True)),
                ('question_fr', models.CharField(max_length=255, null=True)),
                ('answer', wagtail.fields.RichTextField(blank=True)),
                ('answer_en', wagtail.fields.RichTextField(blank=True, null=True)),
                ('answer_es', wagtail.fields.RichTextField(blank=True, null=True)),
                ('answer_fr', wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
