# Generated by Django 5.1.5 on 2025-01-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_fr',
            field=models.TextField(null=True),
        ),
    ]
